### ISSUE TITLE
Why there are two steps to find poolKeys?

### ISSUE THREAD

**Issue by jdbzbug** [precious-void/raydium-swap#4]
// Trying to find pool info in the json we loaded earlier and by comparing baseMint and tokenBAddress
  let poolInfo = raydiumSwap.findPoolInfoForTokens(baseMint, quoteMint)
  console.log('Found pool info')

  if (!poolInfo) poolInfo = await raydiumSwap.findRaydiumPoolInfo(baseMint, quoteMint)

**Comment by precious-void** [comment]
Hey, thanks for the questions. The idea behind this logic is that the first search tries to get the poolKeys from the "cache" (e.g. raydium pools.json that weights a lot and takes a lot of time to download). The problem with this method is that it won't work for newly created token pairs. That's why there is a second method that is a fallback to the first one.

Second method tries to get poolKeys directly from the chain, which solves the problem I had mentioned earlier.

Hope that answers you question 👾
